services:
  app:
    image: "badreddineslaoui/localmindv2-backend:${IMAGE_TAG}"
    container_name: localmindv2-backend
    restart: always
    env_file:
      - .env.laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

  nuxt:
    image: "badreddineslaoui/localmindv2-frontend:${IMAGE_TAG}"
    container_name: localmindv2-frontend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env.nuxt
    depends_on:
      - nginx