services:
  app:
    image: badreddineslaoui/localmindv2-backend:${IMAGE_TAG}
    container_name: backend_green
    env_file: .env.laravel
    networks:
      default:
      proxy_net:
        aliases:
          - backend_green
    restart: always

  nuxt:
    image: badreddineslaoui/localmindv2-frontend:${IMAGE_TAG}
    container_name: frontend_green
    env_file: .env.nuxt
    networks:
      default:
      proxy_net:
        aliases:
          - frontend_green
    restart: always

networks:
  default:
  proxy_net:
    external: true
    name: localmind_proxy