services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - blue_net
      - green_net
    restart: always

networks:
  blue_net:
    external: true
    name: localmind-blue_default
  green_net:
    external: true
    name: localmind-green_default