services:
  caddy:
    image: caddy:alpine
    container_name: caddy
    ports:
      - "80:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - proxy_net
    restart: always

networks:
  proxy_net:
    external: true
    name: localmind_proxy