name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/localmindv2-backend-v2:${IMAGE_TAG} -f backend/Dockerfile.prod.v2 ./backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/localmindv2-frontend-v2:${IMAGE_TAG} -f frontend/Dockerfile.prod ./frontend

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/localmindv2-backend-v2:${IMAGE_TAG}
          docker push ${{ secrets.DOCKER_USERNAME }}/localmindv2-frontend-v2:${IMAGE_TAG}

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            bash /home/ubuntu/localmindv2/deploy-v2.sh ${{ env.IMAGE_TAG }}